name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:   
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:          
          go-version: 1.17.5
          stable: true          
          token: ${{ github.token }}
      - run: cd test && go test -v
        env:
          CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
          CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}            
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
      - run: terraform init
      - id: plan
        run: terraform plan -parallelism=1 -no-color -out=tfplan_add_sa_env_and_cluster    
      - id: apply
        env:
          CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
          CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
        run: terraform apply -parallelism=1 tfplan_add_sa_env_and_cluster
